### PR TITLE
Add support to Plone 5.1, Plone 5.2, Python 3.7 and Python 3.8

### PR DESCRIPTION
**Pull request by wesleybl**

### CODE REVIEW

**Comment by wesleybl** [comment]
New release 1.0.0?

I made changes to the package to work with Python 3 and Plone 5.2. I performed a migration from a portal to Plone 5.2 and Python 3.8.11 with the master branch and it worked correctly.

Could someone please create a 2.0.0 release or give me permission on pypi so I can do it myself?

@garbas @tdesvenain @frapell

I'm asking for PR because issue creation is not enabled in this repository. Can someone please enable?

@mauritsvanrees @jensens

**Comment by wesleybl** [comment]
Someone?

@garbas @tdesvenain @frapell @mauritsvanrees @jensens

**Comment by frapell** [comment]
@wesleybl Sorry, totally missed your first ping... I have released it with a new version number, 0.3.0

I don't seem to have permissions to change settings for this package in order to enable issues, but I seem to have permission to add you as a collaborator in pypi, so you can make new releases if you want. Just let me know your pypi username

**Comment by wesleybl** [comment]
Thanks @frapell !

My pypi user is `wesleybl`

**Comment by wesleybl** [comment]
> I have enabled issues in this repo.

Thanks @mauritsvanrees !

**Pull request merged**
